context:
  version: "0.8.15"

package:
  name: toybox
  version: ${{ version }}

source:
  url: https://github.com/landley/toybox/archive/${{ version }}.tar.gz
  sha256: 52452b68a6cf50f9a9728b0f844b03c4dd1f70463675b202e6cf0475bda3934f

build:
  number: 0
  skip: win
  script:
    content:
      - if: osx
        then:
          - make macos_defconfig toybox HOSTCC="${CC_FOR_BUILD}"
        else:
          - make defconfig toybox HOSTCC="${CC_FOR_BUILD}"
      - install -D -m755 toybox "${PREFIX}/bin/toybox"

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - make
    - sed
    - uutils-coreutils
  host:
    - if: linux
      then: libxcrypt

tests:
  - script:
      - toybox --version
      - toybox --help
      - toybox
  - package_contents:
      strict: true
      bin:
        - toybox

about:
  homepage: https://landley.net/toybox/
  summary: all-in-one Linux command line.
  description: |
    all-in-one Linux command line.
  license: 0BSD
  license_file:
    - LICENSE
  repository: https://github.com/landley/toybox

extra:
  recipe-maintainers:
    - XhstormR
